version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "python"
enabled = true
test_patterns = [
  "tests/**",
  "test_*.py"
]


  [analyzers.meta]
  runtime_version = "3.x.x"
